version: "3.8"

services:
  fuseki:
    container_name: oeh-fuseki
    build: .
    ports:
      - "3030:3030"
    volumes:
      - type: volume
        source: ttl-data
        target: /fuseki-base/databases
    environment:
      ADMIN_PASSWORD: ${PW}
      ENABLE_DATA_WRITE: "true"
      ENABLE_UPDATE: "true"
      QUERY_TIMEOUT: 600000


volumes:
  ttl-data:
