PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix owl: <http://www.w3.org/2002/07/owl#>
PREFIX text: <http://jena.apache.org/text#>
PREFIX sd: <http://www.w3.org/ns/sparql-service-description#>
PREFIX sdo: <http://schema.org/>


SELECT DISTINCT ?lbl
WHERE {
  # ?s text:query (sdo:description 'Mathematik') ;
  ?s text:query (skos:prefLabel 'Deutsch'@de) ;
  skos:prefLabel ?lbl .
  FILTER (lang(?lbl) = 'de')
}
LIMIT 100
