PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix owl: <http://www.w3.org/2002/07/owl#>

SELECT
    ?id
    (lang(?prefLabel) as ?lang)
    ?children

WHERE {
  GRAPH <http://w3id.org/openeduhub/vocabs/discipline/#>
  {
	  ?id skos:prefLabel ?prefLabel .
    OPTIONAL  { ?id skos:narrower ?children . }
	}
}
